version: "2"

services:
  go-live:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./config.toml:/app/config.toml
    ports: 
      - 1935:1935
      - 7001:7001
      - 8090:8090
      - 8040:8040